### ISSUE TITLE
KeyError: 'mt5.1.1'

### ISSUE THREAD

**Issue by codejeam** [ZhuiyiTechnology/t5-pegasus#29]
跑finetune脚本，报如下错误，请问该如何解决？

![1653544327(1)](https://user-images.githubusercontent.com/97791408/170425361-27148dc3-9088-464d-ba9f-de2a481cf0f6.png)

base版和small版都是报这个错误

**Comment by Garethyu** [comment]
你好，请问你解决了这个问题了吗，怎么解决的？

**Comment by codejeam** [comment]
Bert4keras版本不对，新版本里才增加了这个模型

发自我的iPhone

**Comment by Garethyu** [comment]
> Bert4keras版本不对，新版本里才增加了这个模型 发自我的iPhone
> […](#)
> 在 2022年6月5日，下午12:20，Garethyu ***@***.***> 写道： ﻿ 你好，请问你解决了这个问题了吗，怎么解决的？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.

好的，十分感谢！
